### PR TITLE
Increase range for peer dependencies

### PR DESCRIPTION
**Pull request by konstantinmuenster**
Hi Alvar! Thanks for creating this great package - love the approach you took 👏

While installing, I ran into this annoying npm --legacy-peer-deps issue. So I thought increasing the compatibility range for peer deps might be a good idea - assuming that the package works with React 17 too (though I don't know why it shouldn't).

### CODE REVIEW

**Comment by alvarlagerlof** [comment]
That does seem like something I could do. Will get to it tomorrow.

**Comment by alvarlagerlof** [comment]
Did not realize this was a PR. My CI action did not seem to run, so I edited it to hopefully include this PR. Please rebase against master when you can.

**Comment by konstantinmuenster** [comment]
Done 👍

**Comment by alvarlagerlof** [comment]
Merged. A new release was just created automatically. Realizing now that since the commit here did not follow Conventional Commits, the release note is empty. But the change should be there.

**Pull request merged**
